"""2-D quad mesh container (``QuadMesh``), its operations, and smoothing."""

from .assemble import Seam, attach, components, loft, loft_fn, loft_spline, merge, remove, select
from .lift import annulus, extrude, from_grid, sweep, sweep_path
from .lower import boundary_mesh
from .morph import (
    blend,
    mirror,
    offset,
    place_on_path,
    reindex,
    rotate,
    scale,
    transform,
    translate,
)
from .ports import Port, port
from .quadmesh import NO_TAG, QuadMesh
from .quality import order_scan
from .query import (
    area,
    boundary_edges,
    boundary_elements,
    boundary_points,
    bounds,
    centroid,
    element_areas,
    element_blocks,
    plane_normal,
    quality_summary,
    scaled_jacobian,
    tagged_edges,
)
from .shape import (
    box,
    half_box,
    half_ogrid,
    hemisphere,
    ogrid,
    quadrant_core,
    quadrant_ogrid,
    quadrant_seam_fractions,
    rectangle,
    sphere,
    spine_fractions,
    spined_ogrid,
    structured,
    tri_patch,
    tri_patch_tip,
)
from .tag import retag_edge, retag_element, tag_edges

__all__ = [
    "area",
    "bounds",
    "centroid",
    "components",
    "element_areas",
    "element_blocks",
    "mirror",
    "remove",
    "retag_edge",
    "retag_element",
    "tag_edges",
    "select",
    "NO_TAG",
    "Port",
    "QuadMesh",
    "Seam",
    "annulus",
    "attach",
    "assemble",
    "blend",
    "boundary_edges",
    "boundary_elements",
    "boundary_mesh",
    "boundary_points",
    "box",
    "extrude",
    "from_grid",
    "half_box",
    "half_ogrid",
    "hemisphere",
    "lift",
    "loft",
    "loft_fn",
    "loft_spline",
    "lower",
    "merge",
    "morph",
    "offset",
    "ogrid",
    "place_on_path",
    "plane_normal",
    "port",
    "quadrant_core",
    "quadrant_ogrid",
    "quadrant_seam_fractions",
    "order_scan",
    "quality_summary",
    "query",
    "rectangle",
    "reindex",
    "rotate",
    "scale",
    "scaled_jacobian",
    "tagged_edges",
    "shape",
    "sphere",
    "spine_fractions",
    "spined_ogrid",
    "structured",
    "sweep",
    "sweep_path",
    "tag",
    "transform",
    "translate",
    "tri_patch",
    "tri_patch_tip",
]
