"""1-D mesh container (:class:`LineMesh`), its operations, and its shape factories."""

from .assemble import (
    Seam,
    attach,
    components,
    loft,
    loft_fn,
    loft_spline,
    merge,
    refine,
    remove,
    select,
)
from .linemesh import LineMesh
from .morph import blend, mirror, offset, reverse, rotate, scale, transform, translate
from .query import (
    boundary_elements,
    boundary_points,
    bounds,
    centroid,
    element_blocks,
    element_lengths,
    length,
)
from .shape import (
    arc,
    arclength_fractions,
    circle,
    line,
    on_surface,
    path_fractions,
    rectangle,
    sweep_fractions,
)
from .tag import retag_element, retag_point

__all__ = [
    "Seam",
    "attach",
    "bounds",
    "centroid",
    "components",
    "element_blocks",
    "element_lengths",
    "length",
    "mirror",
    "remove",
    "retag_element",
    "retag_point",
    "select",
    "LineMesh",
    "arc",
    "arclength_fractions",
    "assemble",
    "blend",
    "boundary_elements",
    "boundary_points",
    "circle",
    "line",
    "loft",
    "loft_fn",
    "loft_spline",
    "merge",
    "morph",
    "offset",
    "on_surface",
    "path_fractions",
    "query",
    "rectangle",
    "refine",
    "reverse",
    "rotate",
    "scale",
    "shape",
    "sweep_fractions",
    "tag",
    "transform",
    "translate",
]
