"""3-D hex mesh container (``HexMesh``), its operations, and constrained smoothing."""

from .assemble import (
    attach,
    components,
    loft,
    loft_fn,
    loft_spline,
    merge,
    remove,
    select,
)
from .hexmesh import HexMesh
from .lift import (
    adapter,
    annulus,
    bridge,
    extrude,
    from_grid,
    sweep,
    sweep_path,
)
from .lower import boundary_mesh
from .morph import blend, mirror, rotate, scale, transform, translate
from .quality import order_scan
from .query import (
    boundary_elements,
    boundary_face_ids,
    boundary_faces,
    boundary_points,
    bounds,
    centroid,
    classify_points,
    element_blocks,
    element_volumes,
    is_conforming,
    is_overlap_free,
    is_watertight,
    quality_summary,
    report,
    scaled_jacobian,
    tag_report,
    tagged_faces,
    topology_report,
    volume,
)
from .shape import tetra
from .tag import retag_element, retag_face, tag_faces

__all__ = [
    "bounds",
    "centroid",
    "components",
    "element_blocks",
    "element_volumes",
    "mirror",
    "remove",
    "retag_element",
    "retag_face",
    "select",
    "tag",
    "volume",
    "HexMesh",
    "adapter",
    "attach",
    "annulus",
    "assemble",
    "blend",
    "boundary_elements",
    "boundary_face_ids",
    "boundary_faces",
    "boundary_mesh",
    "boundary_points",
    "bridge",
    "classify_points",
    "extrude",
    "from_grid",
    "is_conforming",
    "is_overlap_free",
    "is_watertight",
    "lift",
    "loft",
    "loft_fn",
    "loft_spline",
    "lower",
    "merge",
    "morph",
    "order_scan",
    "quality_summary",
    "query",
    "report",
    "rotate",
    "scale",
    "scaled_jacobian",
    "shape",
    "sweep",
    "sweep_path",
    "tag_faces",
    "tag_report",
    "tagged_faces",
    "tetra",
    "topology_report",
    "transform",
    "translate",
]
